name: Deploy to GitHub Pages and Replace

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Firebase Config
        env:
          API_KEY: ${{ secrets.APIKEY }}
        run: |
          if [ -z "$API_KEY" ]; then echo "SECRET IS EMPTY"; exit 1; fi
          sed -i "s|.*import { firebaseConfig } from .*config.js.*;|const firebaseConfig = $MY_API_KEY;|" auth.html
          echo "Resulting line:"
          grep "const firebaseConfig =" auth.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
