name: Deploy to GitHub Pages and Replace

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Firebase Config
        env:
          DATA: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $DATA
          sed -i "s|.*import { firebaseConfig } from \"./config.js\";|const firebaseConfig = $DATA;|" auth.html
          echo "--- Результат замены ---"
          grep "const firebaseConfig =" auth.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
