name: Deploy to GitHub Pages and Replace

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Firebase Config
        run: |
          sed -i 's|.*import { firebaseConfig } from "./config.js";|const firebaseConfig = ${{ secrets.APIKEY }};|' auth.html
          grep "const firebaseConfig = ${{ secrets.APIKEY }}" auth.html

        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
